# Generated by Django 6.1.2 on 2026-10-08 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt editiert')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Fragetext')),
                ('type', models.CharField(choices=[('MC', 'Multiple Choice (Text)'), ('MCIMG', 'Multiple Choice (Bild)'), ('TR', 'Touch Laufroute')], default='MC', max_length=5)),
                ('points', models.SmallIntegerField(default=0, verbose_name='Punkte')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions/', verbose_name='Bild')),
                ('marked_for_review', models.BooleanField(default=False, verbose_name='Zur Prüfung markiert')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt editiert')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.category', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Frage',
                'verbose_name_plural': 'Fragen',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Antworttext')),
                ('additional_information', models.TextField(blank=True, verbose_name='Zusatzinformation')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Ist korrekt')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/answers/', verbose_name='Bild')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt editiert')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt')),
                ('related_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question')),
            ],
            options={
                'verbose_name': 'Antwort',
                'verbose_name_plural': 'Antworten',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveBigIntegerField(default=0, verbose_name='Gesamtpunktzahl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutzerstatistik',
                'verbose_name_plural': 'Nutzerstatistiken',
            },
        ),
        migrations.CreateModel(
            name='QuestionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_attempts', models.PositiveIntegerField(default=0, verbose_name='Richtige Versuche')),
                ('false_attempts', models.PositiveIntegerField(default=0, verbose_name='Falsche Versuche')),
                ('last_answered', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_progress', to='quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_progress', to=settings.AUTH_USER_MODEL, verbose_name='Nutzer')),
            ],
            options={
                'verbose_name': 'Antwortfortschritt',
                'verbose_name_plural': 'Antwortfortschritte',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
